### PR TITLE
Support nanobind

### PR DESCRIPTION
**Pull request by davidlatwe**
Hi @pthom ,

Thank you for this awesome project. This pull request enabled us to generate ImGui binding with nanobind.

In latest 2 commits, we were even able to generate binding from original ImGui source (non-docking) without the need to patch `IMGUI_BUNDLE_PYTHON_UNSUPPORTED_API`:
* c9d65ee425225d5417fb1373db807565ae9520d6
* 78c7ff5809fd361d57b315f924987c03e5e11c69

At this moment, I have only tested with these two ImGui source:
* @pthom 's ImGui fork, the one resides in [pthom/imgui_bundle](https://github.com/pthom/imgui_bundle)
* Original ImGui [v1.91.3](https://github.com/ocornut/imgui/releases/tag/v1.91.3) (not docking branch)

Did not have all API binding tested, but works in our project so far.

🚨This commit 656a99c68b82512e6a8e2d6816f295da5df688c1 bumped version to `0.999.0`, we need a proper version for this before merge.

### CODE REVIEW

**Comment by davidlatwe** [comment]
Just realized that I have not yet added tests for this. Will see if I can make that happen ASAP.

* [ ] unit tests (code generation)
* [ ] integration tests (bindings tests)

**Comment by pthom** [comment]
Hello,

I added your branch in the repository into a new [nanobind branch](https://github.com/pthom/litgen/tree/nanobind) . I performed a rebase on the main branch before doing so.

The integration went smoothly. I only had to do a few changes, in three commits I added on top of yours:

* Commit https://github.com/pthom/litgen/commit/b5248f402d12e720232974290156219bedb92fc7: fix adapt_c_buffers

I had to do a small fix, following the rebase, because I had added a "contiguous check".
Note: you may want to add such a test for nanobind here: 
https://github.com/pthom/litgen/blob/a3c6671d6109aa90504ceacf834a897ae3af4216/src/litgen/internal/adapt_function_params/_adapt_c_buffers.py#L402-L419

* Commit https://github.com/pthom/litgen/commit/cbc37fe7cab1d5dc42a6fcbee4297fe0be80ae65:
Some very small changes to the unit tests. All unit tests now pass (but they are only testing pybind11 bindings)

* Commit https://github.com/pthom/litgen/commit/a3c6671d6109aa90504ceacf834a897ae3af4216 : fixed a minor mypy warning

----

**Status as of now:**

- [X] nanobind support is available in a dedicated branch in this repo
- [X] all unit tests with pybind11 work. 
- [ ] It would be necessary to add a unit test dedicated to the changes between pybind11 and nanobind
- [ ] It would be necessary to add integration tests for nanobind

As you know more than me about nanobind, could you have a look at this? Do not hesitate to ask for help, I'll be happy to answer questions and to provide help.

**Comment by pthom** [comment]
Hum, setting up the integration test for two different binding types is a bit tricky, especially in the build scripts. Give me some time to have a look at it.

**Comment by davidlatwe** [comment]
Thanks! I should be able to join you on this weekend. 👍🏼

**Comment by pthom** [comment]
Hello,

I added some more commits and reorganized the integration tests to account for nanobind and pybind11 working together in the [integration_tests](https://github.com/pthom/litgen/tree/nanobind/src/litgen/integration_tests) folder of the nanobind branch.

I also added some information in the [integration test Readme](https://github.com/pthom/litgen/blob/nanobind/src/litgen/integration_tests/Readme.md). 

Please read it, as it should help you understand the new folder structure and how to run the tests. 
I advise you to install just (see [just.systems](https://just.systems/)), in order to use the build scripts I provided with it:

```bash
 just -l
Available recipes:
    build_integration_tests_nanobind # Builds the integration tests for nanobind
    build_integration_tests_pybind   # Builds the integration tests for pybind
    default                          # List all available commands
    integration_tests                # Runs all tests for pybind and nanobind (after building the integration tests)
    integration_tests_nanobind       # Runs all tests for nanobind, after building the integration tests
    integration_tests_pybind         # Runs all tests for pybind, after building the integration tests
    mypy                             # Runs mypy on the top level folder (see mypy.ini)
    pytest                           # Just runs pytest (requires that the integration tests have been built)
```


**Here is the current status**

I took some time to correct the compilation of all tests when using nanobind. This was a good occasion for me to look at what modifications you did (and I was pleased).

_What works now:_
- All tests now compile completely with nanobind and pybind11. You can switch between both with `export LITGEN_USE_NANOBIND=ON/OFF` before running `pip install -v -e .` (or use the provided just scripts) 

- trampoline classes & override now compile correctly: I had to do a few adaptations, see 3219a2422447f8831b3e0a9861a364017618644e

- adapt_c_buffers: I did some corrections, see c9a4a7e8eaac6afbd4fa96e7b39776e235cded0d 

- with nanobind, custom python constructors shall use "placement new": I did some related corrections in 618c945942e52dbe324b433cb425a9453f492940 and 789b08c3aee767e66e792b316ab055b8a967254e

- templated buffers: I "lazily corrected" the compilation by disabling this feature at the moment with nanobind. This should be restored in a later step (see 88d2cea6537e9a28875b8b802b5d91d0d3b0c8f8)

_Status of the integration tests_

I made modifications in order to ensure that the tests do compile. I did not check and correct the python tests at the moment (i.e the tests that will check that the bindings do work as expected).

Here is a quick recap of the failing tests as of now:

```bash
> just integration_tests_nanobind
...
...
...
======================================================================================================== short test summary info =========================================================================================================
FAILED src/litgen/integration_tests/mylib/c_style_array_test.py::test_const_array2_add - TypeError: const_array2_add(): incompatible function arguments. The following argument types are supported:
FAILED src/litgen/integration_tests/mylib/c_style_buffer_to_pyarray_test.py::test_add_inside_buffer - Failed: DID NOT RAISE <class 'RuntimeError'>
FAILED src/litgen/integration_tests/mylib/c_style_buffer_to_pyarray_test.py::test_templated_mul_inside_buffer - AttributeError: module 'lg_mylib' has no attribute 'templated_mul_inside_buffer'
FAILED src/litgen/integration_tests/mylib/class_adapt_test.py::test_adapt_constructor - TypeError: __init__(): incompatible function arguments. The following argument types are supported:
FAILED src/litgen/integration_tests/mylib/class_adapt_test.py::test_modify_array_member_via_numpy_array - TypeError: __init__(): incompatible function arguments. The following argument types are supported:
FAILED src/litgen/integration_tests/mylib/mix_adapters_class_test.py::test_template_method - AttributeError: 'lg_mylib._lg_mylib.some_namespace.Blah' object has no attribute 'templated_mul_inside_buffer'
FAILED src/litgen/integration_tests/mylib/modifiable_immutable_test.py::test_adapt_modifiable_immutable_to_return - TypeError: Unable to convert function return value to a Python type! The signature was
FAILED src/litgen/integration_tests/mylib/return_value_policy_test.py::test_return_value_policy - AssertionError: assert 0 == 3
FAILED src/litgen/integration_tests/mylib/template_class_test.py::test_template_class_int - TypeError: __init__(): incompatible function arguments. The following argument types are supported:
FAILED src/litgen/integration_tests/mylib/template_class_test.py::test_template_class_string - TypeError: __init__(): incompatible function arguments. The following argument types are supported:
FAILED src/litgen/integration_tests/mylib/template_function_test.py::test_sum_vector_and_c_array - TypeError: sum_vector_and_c_array_int(): incompatible function arguments. The following argument types are supported:
FAILED src/litgen/integration_tests/mylib/template_function_test.py::test_sum_vector_and_c_array_method - TypeError: sum_vector_and_c_array_int(): incompatible function arguments. The following argument types are supported:
==================================================================================================== 12 failed, 224 passed in 10.76s =====================================================================================================
call_guard_tester
error: Recipe `integration_tests_nanobind` failed on line 25 with exit code 1
```

12 tests out of 224 fail. Seems reasonable.


**The road ahead**

Let me summarize here what remains to be done. 
- [ ] correct integration tests
- [ ] restore templated buffers: I "lazily corrected" the compilation by disabling this feature at the moment with nanobind. This should be restored in a later step (see 88d2cea6537e9a28875b8b802b5d91d0d3b0c8f8)
- [ ] add info about the bindings in the doc. 
- [ ] add pybind11 & nanobind pydef in the [documentation site](https://pthom.github.io/litgen)
- [ ] inform nanobind team, and create a PR so that their doc site (https://nanobind.readthedocs.io/en/latest/) mentions the existence of litgen (which is already mentioned in the pybind11 site)

Please keep me informed on your progress, and do not hesitate to ask for help, or to inform me if you hit a road block or if you feel you do not have enough time.

Many thanks for your help!

**Comment by davidlatwe** [comment]
Hey @pthom 👋🏼 

I pulled your `nanobind` branch and had a spin, the integration test is working here (nanobind tests are not 100% passed yet).

Here are my feedbacks/progress. 😃 

## Use `venv`

I think we should mention Python venv setup in `integration_tests
/Readme.md` before calling `just` recipe.

```powershell
cd src/litgen/integration_tests
python -m venv ./venv
./venv/Scripts/Activate.ps1
pip install -r requirements-dev.txt
```

## Add a few more dependencies in `requirements-dev.txt`

After I setup my `venv` under `integration_tests`, the dependency installed from original requirement file was not enough for me to run tests.

* It installed `litgen` from git main branch, which does not have latest changes we want to test with.
* We need `pytest` and `numpy` for testing.

So I modified it like so:

```requirement.txt
# Install litgen in edit mode (you need to be in the same directory as this requirements-dev.txt)
-e ../../..

# Testing
black
mypy
pytest
numpy
```

## A few changes for making `justfile` to support Powershell

Since I am on Windows and mostly using Powershell, I did a few tweaks for me to run on Powershell. 😄 

```justfile
set windows-shell := ["powershell.exe", "-c"]

[unix]
_pip_install use_nanobind:
    export LITGEN_USE_NANOBIND="{{use_nanobind}}" && cd src/litgen/integration_tests && pip install -v -e . && cd -

[windows]
_pip_install use_nanobind:
    $env:LITGEN_USE_NANOBIND="{{use_nanobind}}"; pushd $pwd; cd src/litgen/integration_tests; pip install -v -e .; popd

# Builds the integration tests for pybind
build_integration_tests_pybind:
    python src/litgen/integration_tests/autogenerate_mylib.py no_generate_file_by_file pybind11
    just _pip_install OFF
    python -c "import lg_mylib"

# Builds the integration tests for nanobind
build_integration_tests_nanobind:
    python src/litgen/integration_tests/autogenerate_mylib.py no_generate_file_by_file nanobind
    just _pip_install ON
    python -c "import lg_mylib"
```


## Tests still run when build failed

The step I took:

1. Run `just integration_tests_pybind`
2. `lg_mylib` generated and installed
3. `pybind11` tests passed 100%
4. Run `just integration_tests_nanobind`
5. Build failed but tests still passed 100%

Clearly the `lg_mylib` being used in step 5 was the one installed from `pybind11` test, which can be confusing. We should ensure tests always run on demanded binding. 🤔 

I am thinking if we can name each binding differently, like `lg_mylib_pybind` and `lg_mylib_nanobind`. And in test module, we import them like this:

```python
if test_pybind:
    import lg_mylib_pybind as lg_mylib
else:
    import lg_mylib_nanobind as lg_mylib
```

Does this make sense?


## Renamed `pybind_mylib.cpp`

I renamed `_pydef_nanobind/pybind_mylib.cpp` to `_pydef_nanobind/nanobind_mylib.cpp`.


## Which branch should I continue?

Should I merge your `nanobind` branch into this one to continue?

Or... I have never used this "Allow edits by maintainers" feature before, but it sounds like you can push your commits into this branch too?



Let me know what you prefer!


<br>

Thanks for your help on this! 🚀

**Comment by pthom** [comment]
Hello @davidlatwe 

I do not have much time today, but to answer your question about which branch to use, you wrote:

> Or... I have never used this "Allow edits by maintainers" feature before, but it sounds like you can push your commits into this branch too?

I never used this too. However, it might work ;-) Could you integrate the changes from my nanobind branch to your nanobind branch and we will continue working on yours? Please note that I had done a rebase of your changes initially.

> I am thinking if we can name each binding differently, like lg_mylib_pybind and lg_mylib_nanobind. 

Sound like a good idea!

**Comment by davidlatwe** [comment]
Hi @pthom 

I have integrated your commit into this branch. It was done by these steps:
1. Rebase this branch onto `main` branch, with conflict resolved
2. Cherry pick your commits

Before doing afore mentioned integration, I tried force-push your branch into this PR directly. But the git diff become un-readable so I did another force-push to correct it.

About supporting Powershell for `just` on Windows, I had a second thought. Since everything works well if using Git-Bash, so I figure it is best to keep it as is.

Will continue the nanobind tests as soon as I can.

**Comment by pthom** [comment]
Hi David,

I had a look at your changes and they look good. I pushed some small modifications:

- Added a bit of documentation explaining how to switch between 
- Some minor corrections and refactoring in lg_mylib/use and __init__.py

Good job, Cheers!

**Comment by pthom** [comment]
Hello again,

I had another look at the failing tests, and as I was suspecting, the code to adapt c buffers is quite complex (and a bit fragile). Making it compatible for pybind together with nanobind is not an easy at all, especially because the ndarray API was completely rewritten for nanobind.  

I am working on some corrections on this part, I will keep you informed.

**Comment by pthom** [comment]
Hi David,

Big thanks for all the great work on this PR! 
Your efforts to add nanobind support and handle the differences with pydef syntax have been incredibly useful, and I’m thrilled with how it turned out! I’ve been testing the new bindings, and they’re working great!

Since the last steps were a bit complex (and needed testing on multiple platforms), I went ahead and wrapped up the remaining tasks to get this PR fully completed.

I hope you’re not discouraged by this — I mainly stepped in because I’m juggling quite a few projects (imgui-bundle, litgen, hello-imgui, cvnp, etc.) and wanted to get this feature integrated into imgui-bundle for some upcoming experiments.

I will merge this PR now, and you will see that the [documentation site](https://pthom.github.io/litgen), now shows bindings for both pybind11 and nanobind.

I’m also planning to propose an update to the nanobind documentation site to mention litgen as a compatible generator.

Your work here has really made an impact! 

Please do not hesitate to add comments in this PR: if you feel more changes are needed, we may pursue it, or open a new PR.

Also, I hope to be able to exchange with you concerning your other open PR on imgui_bundle nanobind support!

Thanks again! 😊

PS: you will see that I added a thank you note in the README

Best,
Pascal

**Comment by pthom** [comment]
See https://github.com/wjakob/nanobind/pull/780 where I propose an update to the nanobind doc

**Pull request merged**
